In [36]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from keras.utils import to_categorical

In [37]:
sentences=["I love machine learning","Machine learnig is amazing","I enjoy learning new things","I like watch movies","I like cricket"]

In [38]:
my_tokenizer=Tokenizer()
my_tokenizer.fit_on_texts(sentences)


In [39]:
my_tokenizer.word_index

{'i': 1,
 'machine': 2,
 'learning': 3,
 'like': 4,
 'love': 5,
 'learnig': 6,
 'is': 7,
 'amazing': 8,
 'enjoy': 9,
 'new': 10,
 'things': 11,
 'watch': 12,
 'movies': 13,
 'cricket': 14}

In [40]:
total_words=len(my_tokenizer.word_index)+1
print(total_words)


15


In [41]:
input_sequences=[]
for i in sentences:
    token_list=my_tokenizer.texts_to_sequences([i])[0]
    for j in range(1,len(token_list)):
        n_gram_sequence=token_list[:j+1]
        input_sequences.append(n_gram_sequence)

In [42]:
print(input_sequences)

[[1, 5], [1, 5, 2], [1, 5, 2, 3], [2, 6], [2, 6, 7], [2, 6, 7, 8], [1, 9], [1, 9, 3], [1, 9, 3, 10], [1, 9, 3, 10, 11], [1, 4], [1, 4, 12], [1, 4, 12, 13], [1, 4], [1, 4, 14]]


In [43]:
max_sequence_len=max([len(x) for x in input_sequences])
print(max_sequence_len)
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))

5


In [44]:
print(input_sequences)

[[ 0  0  0  1  5]
 [ 0  0  1  5  2]
 [ 0  1  5  2  3]
 [ 0  0  0  2  6]
 [ 0  0  2  6  7]
 [ 0  2  6  7  8]
 [ 0  0  0  1  9]
 [ 0  0  1  9  3]
 [ 0  1  9  3 10]
 [ 1  9  3 10 11]
 [ 0  0  0  1  4]
 [ 0  0  1  4 12]
 [ 0  1  4 12 13]
 [ 0  0  0  1  4]
 [ 0  0  1  4 14]]


In [45]:
input=input_sequences[:,:-1]
output=input_sequences[:,-1]

In [46]:
print(input[1])
print(input[1])

[0 0 1 5]
[0 0 1 5]


In [47]:
output_c=to_categorical(output,num_classes=total_words)
output_c[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
import keras
from keras import layers
RNN=keras.Sequential([
    layers.Embedding(total_words,100,input_length=max_sequence_len-1),
    layers.SimpleRNN(150),
    layers.Dense(total_words,activation='softmax')])

In [49]:
RNN.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [51]:
RNN.fit(input,output_c,epochs=100,verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.0667 - loss: 2.6998
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.0667 - loss: 2.6408
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3333 - loss: 2.5823
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4667 - loss: 2.5232
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.4000 - loss: 2.4624
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4000 - loss: 2.3990
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4000 - loss: 2.3324
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4000 - loss: 2.2623
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4000 - loss: 2.1889
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4000 - loss: 2.1127
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4000 - loss: 2.0348
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4000 - los

In [52]:
seed_text=__builtins__.input("Enter the text: ")
token_list=my_tokenizer.texts_to_sequences([seed_text])[0]
token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
predicted=RNN.predict(token_list)
predicted


Enter the text: I love
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 272ms/step


array([[9.3069066e-05, 1.0162211e-04, 9.7368729e-01, 1.4673321e-02,
        2.1209801e-04, 1.3503555e-04, 3.6893965e-04, 3.6913055e-04,
        2.4471935e-04, 2.0151385e-04, 1.0517281e-04, 3.8458875e-04,
        4.8532565e-03, 1.4489167e-05, 4.5557488e-03]], dtype=float32)

In [53]:
predicted=np.argmax(predicted,axis=1)
print(predicted)

[2]


In [54]:
predicted_word=""
for word,index in my_tokenizer.word_index.items():
    if index==predicted:
        predicted_word=word
        break
print(f"The next word is:{predicted_word}")

The next word is:machine
