In [1]:
import numpy as np
a=np.array([2,3,4,5])
print(a)



[2 3 4 5]


In [19]:
a=np.array([2+1j,3,4,5],dtype=complex)
print(a)

[2.+1.j 3.+0.j 4.+0.j 5.+0.j]


In [20]:
import numpy as np
datetime1=np.array(['2023-03-03T12:00:00','2023-06-07T03:01:00'],dtype="datetime64")
a=np.diff(datetime1)
print(datetime1.dtype)
print(a.dtype)

datetime64[s]
timedelta64[s]


In [21]:
from numpy import random
s=random.rand()
b=random.randint([2,3,7,9])
print(s)
print(b)

0.9405004150931284
[1 0 2 0]


In [23]:
a=np.zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
a=np.ones([2,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
a=np.arange(6,100,6)
print(a)

[ 6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96]


In [29]:
a=np.arange(5,100,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [30]:
a=np.linspace(0.11,2.2,8)
print(a)

[0.11       0.40857143 0.70714286 1.00571429 1.30428571 1.60285714
 1.90142857 2.2       ]
